# The default messages language
default-language: en
# the number of players which have to sleep independently from the percentage
# if this is above the playercount in a world all players in the world have to sleep
minPlayers: 2
# the ration of players which have to sleep
# set it to 1 or 100% to use the plugin and normal sleeping behavior but with the benefit of ignored 
sleepPercentage: 0.5
# Speed of time for a smoother transition to the morning. Set to 0 to disable this feature. 
nightSpeed: 300
# Whether or not ignored players should help with the sleeping percentage if they decide to sleep
ignoredHelp: true
# If set to true this will reset the phantom spawn chance for all players in the world when skipping the night
# If set to false it will only reset them for the players that slept in the bed (vanilla behaviour)
resetPhantomsForAll: false
# The Type defines who should get the message.
# Possibly values:
#   noone - Don't display the message to anyone
#   sleeping - Only players who lye in a bed
#   world - Every player who is in the same world
#   server - Every player on the server
# The location defined where the messages gets displayed.
# Possible values:
#   chat - As a chat message
#   title - As a title
#   actionbar - In the action bar
notifications:
  sleep:
    type: "sleeping"
    location: "chat"
  leave:
    type: "sleeping"
    location: "chat"
  wake:
    type: "world"
    location: "chat"
  notify:
    type: "sleeping"
    location: "chat"
  notifyOnSingle:
    type: "sleeping"
    location: "chat"