name: ${project.name}
main: de.themoep.BetterBeds.BetterBeds
version: '${minecraft.plugin.version}'
api-version: 1.13
description: ${project.description}
author: Phoenix616
authors: [NeoTiger]
website: https://github.com/Phoenix616/BetterBeds/
commands:
   betterbeds:
      aliases: [bb]
      description: Main plugin command
      usage: /<command> [reload]
      permission: betterbeds.cmd
      permission-message: You don't have the permission <permission>
permissions:
   betterbeds.cmd:
      description: Gives permission to the command
      default: op
   betterbeds.cmd.reload:
      description: Gives permission to the reload command
      default: op
   betterbeds.ghost:
      description: Makes player to a ghost
      default: false
   betterbeds.ghost.buster:
      description: Some people think giving * is a good idea. This doesn't make them ghosts
      default: false
   betterbeds.sleep:
      description: Gives user ability to sleep
      default: true
   betterbeds.ignore:
      description: Users with this permission don't get calculated when they are online.
      default: false
   betterbeds.allnotifications:
      description: Users with this permission will get all notifications shown no matter the type.
      default: false
